modLoader="javafml"
loaderVersion="[36,)"
license="Public domain"

[[mods]]
modId="armorexchanger"
version="1.1"
displayName="armorexchanger"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/armor-exchanger"
#logoFile="logo.png"
#credits=""
authors="StephenBarnes"
description='''
Swap armor by right-clicking'''

[[dependencies.armorexchanger]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.armorexchanger]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
